### ISSUE TITLE
小程序使用新版wechat-app-mall错误提示405

### ISSUE THREAD

**Issue by qxwo** [JoneXiong/oejia_weshop#3]
![QQ浏览器截图20190308122601](https://user-images.githubusercontent.com/23393355/54064629-15616780-4251-11e9-8c56-6d500d5bd755.png)
![QQ浏览器截图20190308122757](https://user-images.githubusercontent.com/23393355/54064631-1befdf00-4251-11e9-882a-6eadb0439cc2.png)

**Comment by pyrun13** [comment]
某些非核心功能的api接口，模块后端并未实现，欢迎参与，补充

**Comment by JoneXiong** [comment]
某些不影响主要流程的非核心功能的http接口模块后端并未实现，欢迎参与，补充
