### ISSUE TITLE
psycopg2.ProgrammingError: syntax error at or near "ON" 

### ISSUE THREAD

**Issue by gswf2008** [JoneXiong/oejia_weshop#4]
安装报错：
`File "/home/wxm_odoo/odoo-dev/addons/oejia_weshop/models/oe_city.py", line 19, in init
    self.env.cr.execute(init_sql)
  File "/home/wxm_odoo/odoo-dev/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/wxm_odoo/odoo-dev/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near "ON"
LINE 2: ... AT TIME ZONE 'UTC', 1, NOW() AT TIME ZONE 'UTC') ON CONFLIC...`

SQL语法：”INSERT .... ON CONFLICT ...." 需要PostgresSQL 9.4以上，最好在README.md中提醒，我一直用的都是9.3

**Comment by JoneXiong** [comment]
已加入常见注意事项及问题处理
