### ISSUE TITLE
12.0在安装后,在Odoo应用页面找不到小程序

### ISSUE THREAD

**Issue by HelloJasonZhang** [JoneXiong/oejia_weshop#8]
1. oejia_weshop已经放在
odoo安装目录是在/odoo
小程序是放在/odoo/odoo-server/addons/oejia_weshop目录
代码是指是下载12.0的代码分支
![image](https://user-images.githubusercontent.com/9972360/59974926-6e78bf80-95e4-11e9-9c6f-64eb4dca9475.png)

![image](https://user-images.githubusercontent.com/9972360/59974385-2c4c7f80-95de-11e9-9815-8c8d39deffb3.png)

已经安装依赖
pip install -r requirement.txt

2. 打开http://localhost:8069/，没有找到小程序
![1](https://user-images.githubusercontent.com/9972360/59974252-9106da80-95dc-11e9-8325-07d2a1a27cb8.png)

请问下是哪一步做错了？

**Comment by JoneXiong** [comment]
你知道odoo第三方模块的安装基本步骤吗？比如刷新本地模块列表操作

**Comment by HelloJasonZhang** [comment]
本人刚入手Odoo，对于安装第三方模块的安装步骤不是很清楚。
能不能告诉下我，多谢！ 
本人也愿意一起把安装文档补充的更完善，对于新手更友好。
