### ISSUE TITLE
不能安装模块“oejia_weshop”，因为一个外部依赖没有满足:No module named xmltodict 

### ISSUE THREAD

**Issue by HelloJasonZhang** [JoneXiong/oejia_weshop#9]
在安装
不能安装模块“oejia_weshop”，因为一个外部依赖没有满足:No module named xmltodict 
![image](https://user-images.githubusercontent.com/9972360/60036568-188a4180-96e2-11e9-90a7-c32900b41822.png)

本人已经安装成功xmltodict-0.11.0版本。
![image](https://user-images.githubusercontent.com/9972360/60039775-1b893000-96ea-11e9-8193-1d8cd36525b1.png)

Python版本是Python 2.7.15+
![image](https://user-images.githubusercontent.com/9972360/60039722-f694bd00-96e9-11e9-94eb-cc4865125c13.png)

求指导，可能是哪一步错了？

**Comment by JoneXiong** [comment]
你先确定你跑odoo的是哪个python，通常系统不只一个python的

**Comment by HelloJasonZhang** [comment]
自己的坑自己填。
在oejia_weshop里面安装依赖包执行指令错了。
应该是： ` pip3 install -r requirements.txt`

之前错误的执行指令是:  ` pip install -r requirements.txt`
